name: MoarCommands
main: com.rdennings.bkplug.main
version: 0.1a
commands:
   getworld:
      description: Will return the name of the world you are in.
      usage: /getworld
      permission: MoarCommands.getworld
      permission-message: You don't have <permission>
   nick:
      description: Change your nickname to that of your choice.
      usage: /nick <DESIRED NICK>
      permission: MoarCommands.nick
      permission-message: You don't have <permission>
   bannick:
      description: Searches nickname database, then bans the user that the nickname belongs to.
      usage: /bannick <nickname>
      permission: MoarCommands.ban
      permission-message: You don't have <permission>
   kill:
      description: Sends a waffle agent to kill the player.
      usage: /kill <name>
      permission: MoarCommands.kill
      permission-message: You don't have <permission>
   day:
      description: Sets time to day.
      usage: /day
      permission: MoarCommands.day
      permission-message: You don't have <permission>
   night:
      description: Sets time to night.
      usage: /night
      permission: MoarCommands.night
      permission-message: You don't have <permission>
   gm:
      description: Sets time to night.
      usage: /gm <1, 0>
      permission: MoarCommands.gm
      permission-message: You don't have <permission>