name: MoarCommands
main: com.rdennings.bkplug.main
version: 0.2b
commands:
   getworld:
      description: Will return the name of the world you are in.
      usage: /getworld
      permission: MoarCommands.getworld
      permission-message: You don't have <permission>
   day:
      description: Sets the time to day in your current world.
      usage: /day
      permission: MoarCommands.time
      permission-message: You don't have <permission>
   night:
      description: Sets the time to night in your current world.
      usage: /night
      permission: MoarCommands.time
      permission-message: You don't have <permission>
   gm:
      description: Changes your gamemode
      usage: /gm <0; 1; 2; creative; survival; adventure>
      permission: MoarCommands.gm
      permission-message: You don't have <permission>
   rape:
      description: Rapes the said player.
      usage: /rape (player)
      permission: MoarCommands.rape
      permission-message: You don't have <permission>